language: android
sudo: required
jdk: oraclejdk8
before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/
 env:
 global:
 - ANDROID_API=17 #specifies to use android api 17
 - EMULATOR_API=17 #specifies to use android emulator 17
 - ANDROID_BUILD_TOOLS=24.0.2
 - ADB_INSTALL_TIMEOUT=10 # times out after 10 minutes